name: solidsynth

on:
  push:
  workflow_dispatch:

env:
  FLUID_VERSION: "2.2.5"

jobs:
  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        build_arch: ["x64", "arm64"]
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Download and extract FluidSynth
        run: |
          curl -L "https://github.com/FluidSynth/fluidsynth/archive/refs/tags/v${{env.FLUID_VERSION}}.zip" -o fs.zip
          7z x fs.zip
      - name: Download and apply SolidSynth patchset
        working-directory: "fluidsynth-${{env.FLUID_VERSION}}"
        run: |
          curl -L "https://github.com/vgmtrans/solidsynth/archive/refs/tags/v${{env.FLUID_VERSION}}.zip" -o ss.zip
          7z x ss.zip
          Get-Content "solidsynth-${{env.FLUID_VERSION}}/0001-solidsynth-patchset.patch" | patch -p1
      - name: Build SolidSynth
        working-directory: "fluidsynth-${{env.FLUID_VERSION}}"
        run: |
          mkdir "solidsynth-msvc2019-${{matrix.build_arch}}" && echo "Made output dir solidsynth-msvc2019-${{matrix.build_arch}}"
          # We want a build with just WaveOut, DirectSound and WASAPI
          cmake -B build . -DCMAKE_INSTALL_PREFIX="./solidsynth-msvc2019-${{matrix.build_arch}}" -A ${{matrix.build_arch}} -T v142 -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 -Denable-ipv6=0 -Denable-network=0 -Denable-aufile=0 -Denable-winmidi=0 -Denable-libsndfile=0  -DNO_GUI=1 -Denable-jack=0 -Denable-pulseaudio=0 -Denable-ladspa=0 -Denable-dbus=0 -Denable-readline=0 -Denable-sdl2=0 -Denable-libinstpatch=0
          # Need to specify "Release" again because of the VS generator
          cmake --build build --config Release --parallel
          cmake --build build --target install
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: "solidsynth-msvc2019-${{matrix.build_arch}}"
          path: "fluidsynth-${{env.FLUID_VERSION}}/solidsynth-msvc2019-${{matrix.build_arch}}"
          
